spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wjc12345
    url: jdbc:mysql://49.235.76.87/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
