spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wjc12345
    url: jdbc:mysql://49.235.76.87/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
  port: 80
  error:
    include-exception: true
    include-message: always